### PR TITLE
Add qflow namespace, random seed, and fix TBB/OpenMP issues

### PR DESCRIPTION
**Pull request by DarkDefender**
Added namespace to guard against redefinition issues when used in larger
projects that might have classes using the same name.

Added a settable random seed number to make sure that the output is
easily reproducible.

Fixed building with TBB and OpenMP.
For OpenMP, some for loop threading where removed as they were not
thread safe and would lead to different output meshes.

This is part of my work on #32

### CODE REVIEW

**Comment by hjwdzh** [comment]
I notice that you have made some changes about random seed and other changes (cols() -> size()). I am not sure  whether size() is the right thing to do. If the matrix is Nx3, cols() = N and size() = N*3. Do you think the original code is wrong with cols()?

**Comment by DarkDefender** [comment]
I changed those to get TBB support to build. When I complied that code it complained that `V` (in this case a `std::vector`, did not have `cols()` so I looked at the other code in that function and it used `size()` instead.

Perhaps we should rename the variable to avoid and confusion?

**Comment by DarkDefender** [comment]
I forgot to mention that I did check if the output changed before and after my changes (using `diff --brief` on the output `.obj`). It seems like the same result as before is generated.

**Comment by hjwdzh** [comment]
Thanks for checking. However, it may cause differences in other models.

**Comment by DarkDefender** [comment]
I'm guessing you have more robust testing suite than me.
Let me know if you find any issues and I'll try to fix them.

**Pull request merged**
